### ISSUE TITLE
Come up with a plan for using the Acknowledger module

### ISSUE THREAD

**Issue by swelham** [SeatedInc/faktory_worker#16]
The acknowledger module allows us to hook into the broadway pipeline and handle the outcome of a message. Most importantly this is where we can capture failed messages (pushed faktory jobs) and allow the user of the library to choose what to do with this.

Likely actions would be to throw the message away if it's not important or maybe push the message back into broadway (via `Worker.perform_async` maybe).

Currently we ignore the message outcomes meaning we will lose jobs that fail, for example if there are network issues.

**Comment by john-griffin** [comment]
Seems like we should retry until the connection comes back? I wouldn't expect to lose any jobs I sent to faktory.

**Comment by swelham** [comment]
Exactly, it's more a question of where should that logic live. Should the user of this lib have the option to handle that and decide or should we always be throwing the message back into broadway and hide this complexity.
