### ISSUE TITLE
Workout out logging approach

### ISSUE THREAD

**Issue by swelham** [SeatedInc/faktory_worker#18]
We need to offer some sort of logging for at very least when things go wrong (i.e. unable to connect to faktory) and potentially some form of debug logging which might output details such as successful connections.

Logging should be minimal by default so that it doesn't flood the terminal window whilst in dev. It should also be configurable to allow different log levels to be set in the faktory worker config.

**Comment by john-griffin** [comment]
Are there any other elixir libraries that you consider to have a good logging approach?

**Comment by swelham** [comment]
We spoke about this over a call but thought I would document the outcome here.

We will add the following basic logging.
* [ ] Log when jobs a scheduled
* [ ] Log when jobs run to successful completion (`ACK` message to faktory)
* [ ] Log when jobs fail (`FAIL` message to faktory)
* [ ] Log when heartbeat success changes (command success, not state changes)

**Comment by jnylen** [comment]
Hi @swelham,

I would suggest looking into telemetry, see: https://github.com/elixir-ecto/ecto/commit/ee8a9ea002f8809825d3bd5a3bc34aa863f223ee

**Comment by swelham** [comment]
Hi @jnylen 

Thanks for the pointer, I will definitely check it out 👍

**Comment by jnylen** [comment]
Hi @swelham,
By the looks of things, telemetry was not implemented. Is this something that will be implemented at a later date? Or will I have to fork to get this added?

**Comment by john-griffin** [comment]
@jnylen we will probably add something like this at some point but right now we are still working towards getting the library fully compatible with faktory. Feel free to open a PR for this if you feel it is urgent.

**Comment by swelham** [comment]
Just in case anyone finds this issue we have now integrated telemetry in #75
