### ISSUE TITLE
Broadway buffer config

### ISSUE THREAD

**Issue by swelham** [SeatedInc/faktory_worker#30]
Currently the Broadway producer has a buffer limit of 10k messages per producer which comes from the defaults set in GenStage.

Lets update this to default to `:infinity` so faktory worker's default is to never discard jobs when pushing to faktory. This should also be overridable at the faktory worker level under the pool settings.

Might be worth a read of these docs about genstage buffering https://hexdocs.pm/gen_stage/GenStage.html#module-buffering.

**Comment by john-griffin** [comment]
Done in #45
