### ISSUE TITLE
Handle ssl error in worker server

### ISSUE THREAD

**Issue by swelham** [SeatedInc/faktory_worker#48]
In production we have seen the following error in our logs.

```
Elixir.FunctionClauseError: no function clause matching in FaktoryWorker.Worker.Server.handle_info/2
  File "lib/faktory_worker/worker/server.ex", line 35, in FaktoryWorker.Worker.Server.handle_info/2
  File "gen_server.erl", line 637, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 711, in :gen_server.handle_msg/6
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3
```

With the first argument being passed into `handle_info`.

```
{:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.786>, :tls_connection, :undefined}, [#PID<0.3043.0>, #PID<0.3037.0>]}}
```

We should try and replicate this locally and maybe handle this error case as part of the libraries retry connection logic.

**Comment by beerlington** [comment]
Any idea why this is happening or if it's affecting jobs?

**Comment by swelham** [comment]
I think this may have occurred during the application startup but I'm not 100% sure on that. I looks like it might be something to do with starting a large batch of workers at once.

It didn't effect any jobs since it only happened on some of the workers and the failed ones successfully connected within a few seconds when issuing their next fetch.
